# Generated by Django 3.0.3 on 2020-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='userType',
        ),
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.TextField(choices=[('US', 'Normal User'), ('TS', 'Ticket Seller'), ('AN', 'Announcer')], default='US'),
        ),
    ]
