# Generated by Django 3.0.5 on 2020-04-27 16:04

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'PREFER')], default=account.utils.GenderTypes['PREFER']),
        ),
    ]
