# Generated by Django 3.0.3 on 2020-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announce_time',
            new_name='announcement_datetime',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='announce_text',
            new_name='announcement_text',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
