# Generated by Django 3.0.3 on 2020-04-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20200428_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_title',
            field=models.TextField(null=True),
        ),
    ]
