# Generated by Django 3.0.3 on 2020-04-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20200428_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement_text',
            new_name='announce_text',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement_datetime',
            new_name='announce_time',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_title',
        ),
    ]
