# Generated by Django 3.0.5 on 2020-04-28 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_text', models.TextField()),
                ('announce_time', models.DateTimeField()),
                ('view_count', models.IntegerField()),
                ('announcer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Announcer')),
            ],
        ),
    ]
