# Generated by Django 3.0.4 on 2020-04-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='view_count',
        ),
    ]
