# Generated by Django 3.0.3 on 2020-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
