# Generated by Django 3.0.5 on 2020-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announce_text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
