# Generated by Django 3.0.5 on 2020-04-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_announce_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcer',
            new_name='announcer_user',
        ),
    ]
