# Generated by Django 3.0.5 on 2020-04-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_announcer'),
        ('announcement', '0004_auto_20200426_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Announcer'),
        ),
        migrations.DeleteModel(
            name='Announcer',
        ),
    ]
