# Generated by Django 3.0.5 on 2020-04-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionInformation', models.TextField()),
                ('transactionStatus', models.BooleanField()),
                ('buyDate', models.DateField()),
                ('bookingStatus', models.BooleanField()),
                ('boardingTrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Timetable')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
