# Generated by Django 3.0.4 on 2020-04-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fromStation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fromStation', to='schedule.Timetable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='toStation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='toStation', to='schedule.Timetable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='boardingTrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Train'),
        ),
    ]
