# Generated by Django 3.0.4 on 2020-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200429_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bookingStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transactionInformation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transactionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
