# Generated by Django 3.0.5 on 2020-05-04 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200429_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='boardingTrain',
            new_name='boarding_train',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='bookingStatus',
            new_name='booking_status',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='buyDate',
            new_name='buy_date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='fromStation',
            new_name='from_station',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='toStation',
            new_name='to_station',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='transactionInformation',
            new_name='transaction_information',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='transactionStatus',
            new_name='transaction_status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='travel_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
