# Generated by Django 3.0.5 on 2020-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainName', models.TextField()),
                ('trainType', models.TextField()),
                ('arrivedTime', models.DateTimeField()),
                ('departedTime', models.DateTimeField()),
                ('fromStation', models.TextField()),
                ('toStation', models.TextField()),
            ],
        ),
    ]
