# Generated by Django 3.0.5 on 2020-04-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.TextField()),
                ('english_station_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.TextField()),
                ('train_type', models.TextField(choices=[('EX', 'Express'), ('LC', 'Local')], default='LC')),
                ('amount_of_passenger', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_time', models.TimeField(null=True)),
                ('departed_time', models.TimeField(null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Train')),
            ],
        ),
    ]
