# Generated by Django 3.0.3 on 2020-05-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_name',
        ),
    ]
