# Generated by Django 3.0.5 on 2020-04-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.TextField()),
                ('train_type', models.TextField(choices=[('EX', 'Express'), ('LC', 'Local')], default='LC')),
                ('amount_of_passenger', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('train_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schedule.Train')),
                ('train_type', models.TextField()),
                ('arrived_time', models.DateTimeField()),
                ('departed_time', models.DateTimeField()),
                ('from_station', models.TextField()),
                ('to_station', models.TextField()),
            ],
        ),
    ]
