# Generated by Django 3.0.5 on 2020-04-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200423_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='from_station',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='to_station',
        ),
        migrations.AddField(
            model_name='timetable',
            name='station_id',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Station'),
        ),
    ]
