# Generated by Django 3.0.3 on 2020-05-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_station_station_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='english_station_name',
            new_name='station_name',
        ),
    ]
