# Generated by Django 3.0.5 on 2020-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200424_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='english_station_name',
            field=models.TextField(null=True),
        ),
    ]
