# Generated by Django 3.0.5 on 2020-04-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_station_english_station_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='train_type',
        ),
    ]
