# Generated by Django 3.0.5 on 2020-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_timetable_train_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='arrived_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='departed_time',
            field=models.TimeField(),
        ),
    ]
