# Generated by Django 3.0.3 on 2020-04-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200424_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='station_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Station'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='train_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Train'),
        ),
    ]
