# Generated by Django 3.0.3 on 2020-04-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20200424_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Station'),
        ),
    ]
