# Generated by Django 3.0.3 on 2020-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20200424_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='arrived_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='departed_time',
            field=models.TimeField(null=True),
        ),
    ]
